language: node_js
node_js:
  - "0.10"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm test
  - cat "`ls coverage/**/lcov.info | head -n 1`" | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
